; Panic Button Hotkey for Bybit-Futures-Bot
; Shift+T triggers emergency panic procedure
; Author: Generated by Claude Code
; Version: 1.0

#NoEnv
#SingleInstance Force
#Persistent

; Configuration
PANIC_URL := "http://127.0.0.1:8787/panic"
STATUS_URL := "http://127.0.0.1:8787/panic/status"
RESET_URL := "http://127.0.0.1:8787/panic/reset"
CURL_PATH := "curl.exe"  ; Assumes curl is in PATH

; Initialization
TrayTip, Panic Button, 🔥 Hotkeys loaded successfully!, 3

; Shift+T hotkey - PANIC with confirmation (MAIN BUTTON)
+t::
    ; Show confirmation dialog for safety
    MsgBox, 4, 🚨 PANIC BUTTON CONFIRMATION,
    (
    ⚠️  EMERGENCY PANIC BUTTON  ⚠️

    This will IMMEDIATELY:
    • STOP all trading
    • CANCEL ALL orders on ALL symbols
    • CLOSE ALL positions with market orders
    • LOCK the system until manual reset

    💰 This affects REAL MONEY!

    Are you absolutely sure you want to continue?
    )

    IfMsgBox Yes
    {
        ; Execute panic request
        TrayTip, Panic Button, 🚨 EXECUTING EMERGENCY PANIC..., 5, 1

        ; Show progress in system tray
        Menu, Tray, Icon, shell32.dll, 3  ; Warning icon

        ; Execute curl command
        RunWait, %CURL_PATH% -X POST %PANIC_URL% -w "Status: %%{http_code}" -s, , Hide, PID

        ; Restore normal tray icon
        Menu, Tray, Icon

        ; Show completion notification
        TrayTip, Panic Button, ✅ Panic procedure sent! Check Telegram for results., 8

        ; Play system sound
        SoundPlay, *64  ; Critical stop sound
    }
    else
    {
        TrayTip, Panic Button, ❌ Panic cancelled by user., 3
    }
return

; Alternative: Ctrl+Alt+Shift+T (INSTANT - No confirmation)
^!+t::
    TrayTip, Panic Button, 🚨 INSTANT EMERGENCY PANIC TRIGGERED!, 5, 3
    Menu, Tray, Icon, shell32.dll, 3  ; Warning icon

    RunWait, %CURL_PATH% -X POST %PANIC_URL% -s, , Hide

    Menu, Tray, Icon
    TrayTip, Panic Button, ✅ Emergency panic executed!, 8
    SoundPlay, *64
return

; Status check: Ctrl+Alt+S
^!s::
    TrayTip, Panic Button, 📊 Checking panic status..., 2

    ; Get status and parse
    RunWait, %CURL_PATH% -s %STATUS_URL% -o status_temp.json, , Hide

    ; Try to read and display status
    FileRead, StatusJson, status_temp.json
    if (StatusJson != "")
    {
        ; Simple status display - would need JSON parser for full parsing
        if InStr(StatusJson, "panic_tripped")
        {
            if InStr(StatusJson, """panic_tripped"": true")
                TrayTip, Panic Status, 🔒 SYSTEM LOCKED - Panic active, 5, 2
            else if InStr(StatusJson, """trading_enabled"": true")
                TrayTip, Panic Status, ✅ System operational - Trading enabled, 3
            else
                TrayTip, Panic Status, ⚠️ Trading disabled, 3, 1
        }
        else
        {
            TrayTip, Panic Status, ❓ Status check failed, 3, 3
        }
    }

    ; Cleanup temp file
    FileDelete, status_temp.json
return

; Reset (with confirmation): Ctrl+Alt+R
^!r::
    MsgBox, 4, 🔓 Panic Reset Confirmation,
    (
    Reset panic state and re-enable trading?

    This will:
    • Remove panic lock
    • Re-enable trading
    • Allow new orders/positions

    ⚠️ Only do this if you've verified all positions
    and orders are properly closed!

    Continue with reset?
    )

    IfMsgBox Yes
    {
        TrayTip, Panic Reset, 🔓 Attempting to reset panic state..., 3
        RunWait, %CURL_PATH% -X POST %RESET_URL% -s, , Hide
        TrayTip, Panic Reset, ✅ Reset command sent. Check results., 5
    }
return

; Health check: Ctrl+Alt+H
^!h::
    TrayTip, Health Check, 🏥 Checking server health..., 2
    RunWait, %CURL_PATH% -s http://127.0.0.1:8787/healthz, , Hide
    TrayTip, Health Check, ✅ Health check completed, 3
return

; Help: F1 or Ctrl+Alt+F1
F1::
^!F1::
    MsgBox, 0, 🔥 Panic Button Hotkeys,
    (
    BYBIT FUTURES BOT - PANIC BUTTON CONTROLS

    🚨 EMERGENCY CONTROLS:
    Shift + T                = Panic with confirmation
    Ctrl + Alt + Shift + T   = INSTANT panic (no confirmation)

    📊 STATUS & MANAGEMENT:
    Ctrl + Alt + S          = Check panic status
    Ctrl + Alt + R          = Reset panic (with confirmation)
    Ctrl + Alt + H          = Health check
    F1 / Ctrl + Alt + F1    = Show this help

    ⚠️  WARNINGS:
    • These hotkeys affect REAL MONEY
    • Always verify positions before reset
    • Use confirmation dialogs when possible
    • Check Telegram for execution results

    🔗 Server: http://127.0.0.1:8787
    )
return

; Emergency exit hotkey (in case script misbehaves)
^!Escape::
    MsgBox, 4, Exit Hotkey Script, Exit the panic button hotkey script?
    IfMsgBox Yes
        ExitApp
return

; Tray menu customization
Menu, Tray, NoStandard
Menu, Tray, Add, 🚨 Execute Panic (Shift+T), ExecutePanic
Menu, Tray, Add
Menu, Tray, Add, 📊 Check Status (Ctrl+Alt+S), CheckStatus
Menu, Tray, Add, 🔓 Reset Panic (Ctrl+Alt+R), ResetPanic
Menu, Tray, Add, 🏥 Health Check (Ctrl+Alt+H), HealthCheck
Menu, Tray, Add
Menu, Tray, Add, 📖 Show Help (F1), ShowHelp
Menu, Tray, Add
Menu, Tray, Add, 🚪 Exit, ExitScript

; Tray menu handlers
ExecutePanic:
    Send, +t
return

CheckStatus:
    Send, ^!s
return

ResetPanic:
    Send, ^!r
return

HealthCheck:
    Send, ^!h
return

ShowHelp:
    Send, {F1}
return

ExitScript:
    ExitApp
return

; Show startup message
TrayTip, Panic Button,
(
🔥 Hotkeys Active!

Press F1 for help or right-click tray icon.
Server: 127.0.0.1:8787

⚠️ Use responsibly - affects real money!
), 5

return